RentCar/Models/Rents.cs
namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Rents
    {
        [Key]
        public int Rent_ID { get; set; }

        public int? Client_ID { get; set; }

        public int Car_ID { get; set; }

        public int? Operator_ID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime StartData { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime EndData { get; set; }

        [Required]
        public double Price { get; set; }

        public bool Driver { get; set; }

        public virtual Car Car { get; set; }

        public virtual Client Client { get; set; }

        public virtual ApplicationUser ApplicationUser { get; set; }

    }
}

RentCar/Controllers/RentsController.cs
using RentCar.Interfaces;
using RentCar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using RentCar.ViewModels;
using PagedList;

namespace RentCar.Controllers
{
    public class RentsController : Controller
    {
        private readonly IClientRepository _clientRep;
        private readonly IDistrictRepository _districtRep;
        private readonly IAddressRepository _addressRep;
        private readonly ICityRepository _cityRep;
        private readonly IRentsRepository _rentsRep;
        private readonly ICarRepository _carRep;
        private readonly IDiscountRepository _discountRep;

        public RentsController(IRentsRepository rentsRep, IClientRepository clientRep, IDistrictRepository districtRep, 
            IAddressRepository addressRep, ICityRepository cityRep, ICarRepository carRep, IDiscountRepository discountRep)
        {
            _clientRep = clientRep;
            _districtRep = districtRep;
            _addressRep = addressRep;
            _cityRep = cityRep;
            _rentsRep = rentsRep;
            _carRep = carRep;
            _discountRep = discountRep;
        }
        

        public ActionResult Index(string searchPhone, int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            if (searchPhone != null)
            {
                var findByPhone = _rentsRep.FindByPhone(searchPhone);

                if (findByPhone != null)   { return View(findByPhone.OrderBy(x => x.Client.Name).ToPagedList(pageNumber, pageSize)); }
            }
            return View(_rentsRep.GetAll().OrderBy(x => x.Client.Name).ToPagedList(pageNumber, pageSize));
        }


        public ActionResult Details(int id)
        {
            var rent = _rentsRep.GetById(id);
            var car = _carRep.GetById(rent.Car_ID);
            var client = _clientRep.GetById((int)rent.Client_ID);

            var rentDetails = new RetnsViewModels()
            {
                Brand = car.Brand,
                Model = car.Model,
                Engine = car.Engine,
                Color = car.Color,
                StartData = rent.StartData,
                EndData = rent.EndData,
                Price = rent.Price,
                Driver = rent.Driver,
                Name = client.Name,
                Surname = client.Surname,
                Phone = client.Phone,
                Email = client.Email,
                District = client.Addres.District.Name,
                City = client.Addres.City.Name,
                Street = client.Addres.Street,
                Flat = client.Addres.Flat
            };
            return View(rentDetails);
        }

        // If the user did earlier rental
        // We are finding his
        public ActionResult OldUser(int? carId, string searchPhone)
        {
            if (searchPhone != null)
            {
                var findUser = _clientRep.GetByPhone(searchPhone);
                if (findUser != null)   { ViewBag.Client = findUser; }
            }

            if (carId == null || carId <= 0)
            {
                var nullCar = new Car() { Car_ID = 0, Model = "Select Car" };
                ViewBag.CurentCar = nullCar;
            }
            else
            {
                ViewBag.CurentCar = _carRep.GetAll().Where(i => i.Car_ID == carId).FirstOrDefault();
            }


            ViewBag.Car = _carRep.GetAll();

            return View();
            
        }

        public ActionResult OrderOldClient(Rents rent)
        {
            if (ModelState.IsValid)
            {
                double price = _carRep.GetAll().Where(i => i.Car_ID == rent.Car_ID)
                    .Select(p => p.Price).FirstOrDefault();

                rent.Price = TotalPriceRent(rent.StartData, rent.EndData, price);
                _rentsRep.Create(rent);
                _rentsRep.Save();
                SaveInSession(rent.Car_ID, rent);
            }

            return RedirectToAction("OldUser");
        }

        // GET: Rents/Create
        public ActionResult Create(int? id)
        {

            if(id == null)
            {
                var nullCar = new Car() { Car_ID = 0, Model = "Select Car" };
                ViewBag.CurentCar = nullCar;
            }
            else
            {
                ViewBag.CurentCar = _carRep.GetAll().Where(i => i.Car_ID == id).FirstOrDefault();
                ViewBag.CarInfo = _carRep.GetById((int)id);
            }

            var c =_districtRep.GetAll();
            ViewBag.Car = _carRep.GetAll();
            ViewBag.District = c;
            
            return View();
        }
        
        [HttpPost]
        public ActionResult Create(RetnsViewModels rentV, int cityDropDown )
        {
            try
            {

                // Insert addres for client and return last ID
                int addressId = InsertAddresReturnID(rentV, cityDropDown);

                // Insert client and return last ID
                int clinetId = InsertClientReturnID(rentV, addressId);

                // Get price for selected car
                double price = _carRep.GetAll().Where(i => i.Car_ID == rentV.Car_ID)
                    .Select(p => p.Price).FirstOrDefault();

                var rent = new Rents();
                rent.Car_ID = rentV.Car_ID;
                rent.Client_ID = clinetId;
                rent.Driver = rentV.Driver;
                rent.StartData = rentV.StartData;
                rent.EndData = rentV.EndData;
                rent.Price = TotalPriceRent(rentV.StartData, rentV.EndData, price);
                //if (Request.IsAuthenticated) { rent.Operator_ID = User.Identity.GetUserId().AsInt(); }

                _rentsRep.Create(rent);
                _rentsRep.Save();
                SaveInSession(rentV.Car_ID, rent);

                return RedirectToAction("Index", "Home");
            }
            catch(Exception e)
            {
                return View(e);
            }
        }

        private void SaveInSession(int carID, Rents rent)
        {
            var car = _carRep.GetById(carID);

            ShopViewModels shopView = new ShopViewModels()
            {
                CarID = car.Car_ID,
                Model = car.Model,
                Brand = car.Brand,
                StartData = rent.StartData,
                EndData = rent.EndData,
                Price = rent.Price,
                RentID = rent.Rent_ID
            };

            // Insert in Cookie client's shopping
            if (Session["FreshOrder"] != null)
            {
                var FOrder = new List<ShopViewModels>();
                FOrder.AddRange(Session["FreshOrder"] as List<ShopViewModels>);
                FOrder.Add(shopView);
            }
            else
            {
                var FOrder = new List<ShopViewModels>();
                FOrder.Add(shopView);
                Session["FreshOrder"] = FOrder;
            }
        }

        // Insert client and return ID
        private int InsertClientReturnID(RetnsViewModels rentV, int addressId)
        {
            var client = new Client()
            {
                Name = rentV.Name,
                Surname = rentV.Surname,
                Email = rentV.Email,
                Idnp = rentV.Idnp,
                Phone = rentV.Phone,
                Addres_ID = addressId
            };

            _clientRep.Create(client);
            _clientRep.Save();
            return client.Client_ID;
        }

        private int InsertAddresReturnID(RetnsViewModels rentV, int cityDropDown)
        {
            var address = new Addres()
            {
                City_ID = cityDropDown,
                District_ID = rentV.District_ID,
                Flat = rentV.Flat,
                Street = rentV.Street
            };

            _addressRep.Create(address);
            _addressRep.Save();
            return address.Addres_ID;;
        }

        public double TotalPriceRent(DateTime startDate, DateTime endDate, double price)
        {
            if(price == 0) { return 0; }
            var days = ((endDate - startDate).Days);
            var percent = _discountRep.PercentForDays(days);
            var discount = (percent / 100) * (days * price);
            var totalPrice = (days * price) - discount;

            return totalPrice;
        }


        public ActionResult Delete(int id)
        {
            return View(_rentsRep.GetById(id));
        }

        // POST: Rents/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
               _rentsRep.Delete(id);
               _rentsRep.Save();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RentCar/Views/Rents/Create.cshtml
@using RentCar.Models
@model RentCar.Models.RetnsViewModels


@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Scripts.Render("~/Scripts/jquery.validate.min.js")
@Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js") 

<h3 class="text-center">Rent your favourite car</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
            </div>

            <div class="col-sm-5">
                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <div class="col-sm-4">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control text-center", placeholder = "First Name" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-sm-4">
                            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control text-center", placeholder = "Surname" } })
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-12">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control text-center", placeholder = "E-mail address" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-12">
                            @Html.EditorFor(model => model.Idnp, new { htmlAttributes = new { @class = "form-control text-center", placeholder = "Identity number" } })
                            @Html.ValidationMessageFor(model => model.Idnp, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-12">
                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control text-center", placeholder = "Phone number" } })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-4">
                            @Html.DropDownListFor(m => m.District_ID, new SelectList(ViewBag.District, "District_iD", "Name"), "Select district", new { @class = "form-control text-center", onchange = "DropDownCities2()", id = "DropDownDistrict" })
                            @Html.ValidationMessageFor(model => model.District_ID, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-sm-4"><select name="cityDropDown" class="form-control" id="cityDropDown"></select></div>

                    </div>
                    <div class="form-group">
                        <div class="col-sm-4">
                            @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control text-center", placeholder = "Street name" } })
                            @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-sm-4">
                            @Html.EditorFor(model => model.Flat, new { htmlAttributes = new { @class = "form-control text-center", placeholder = "Flat number" } })
                            @Html.ValidationMessageFor(model => model.Flat, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-sm-5">

                <div class="form-horizontal">
                    <hr />
                    <div class="form-group">
                        @Html.DropDownListFor(m => m.Car_ID,
                            new SelectList(ViewBag.Car, "Car_ID", "Brand", ViewBag.CurentCar.Car_ID),
                            "Change Car",
                            new {@class = "form-control", @placeholder = "Category"})
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.StartData, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>

                    <div class="form-group">
                        @Html.EditorFor(model => model.StartData, new { htmlAttributes = new { @class = "form-control", type = "date", id="startData" } })
                        @Html.ValidationMessageFor(model => model.StartData, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EndData, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>

                    <div class="form-group">
                        @Html.EditorFor(model => model.EndData, new { htmlAttributes = new { @class = "form-control", type = "date", id="endData",  onchange="CalculatePrice()" } })
                        @Html.ValidationMessageFor(model => model.EndData, "", new { @class = "text-danger" })
                    </div>                    
                    <div class="form-group">
                        @Html.CheckBoxFor(m => m.Driver, new {@style="height: 17px" })
                        <label>Include driver</label>
                    </div>
                    <div class="PriceCarMain">
                        <h3 id="priceCalc">Total price: @ViewBag.CurentCar.Price &euro;</h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group col-md-offset-4">
            <div class="col-sm-2">
                <input type="submit" value="Send Order" class="btn btn-success btn-lg btn-block"/>
            </div>
            <div class="col-sm-2">
                @Html.ActionLink("I am a old user", "OldUser", "Rents", new {carId = ViewBag.CurentCar.Car_ID}, new {@class = "btn btn-danger btn-lg"})

            </div>
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    function CalculatePrice() {
        var startData = $("#startData").val();
        var endData = $("#endData").val();
        var curentPrice = @(ViewBag.CurentCar.Price);
        debugger 
        $.ajax({
            url: '/Rents/TotalPriceRent',
            type: 'POST',
            data:
            {
                startDate: startData,
                endDate: endData,
                price: curentPrice
            }
            ,
            success: function (result) {
                console.log("MDa");
                $("#priceCalc").html("Total price: " + result+" &euro; ");
            },
            error: function (err) {
                alert("error " + err.toString() + err.message);
            }
        });
    }

</script>

RentCar/Views/Rents/Delete.cshtml
@model RentCar.Models.Rents

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Rents</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Car.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Client.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Operator_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Operator_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartData)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartData)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndData)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndData)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RentCar/Views/Rents/Details.cshtml
@model RentCar.Models.RetnsViewModels

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="row details">
    <hr />
    <div class="col-sm-6 ">
        <h2 >Information client</h2>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Surname)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Surname)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Phone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Phone)
            </dd>
            
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.District)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.District)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.City)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.City)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Street)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Street)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Flat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Flat)
            </dd>
        </dl>

    </div>
    <div class="col-sm-6">
        <h2>Information rent</h2>
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.Brand)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Brand)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Model)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Model)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Engine)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Engine)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Color)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Color)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Driver)
            </dt>

            <dd>
                @(Model.Driver?"Yes":"No")
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StartData)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StartData)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EndData)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EndData)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
               &euro; @Html.DisplayFor(model => model.Price)
            </dd>


        </dl>
    </div>  
    
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Rent_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RentCar/Views/Rents/Index.cshtml
@model PagedList.IPagedList<RentCar.Models.Rents>
@using PagedList.Mvc;
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<p>
    @Html.ActionLink("New order", "Create", "Rents", null, new { @class = "btn btn-md btn-primary" })
</p>

@using (Html.BeginForm("Index", "Rents", FormMethod.Post))
{
    <div class="form-group row">
        <div class="col-sm-2">
            @Html.TextBox("searchPhone", null, new { @class = "form-control ", placeholder = "Phone number" })
            <input type="submit" value="Find" class="btn btn-success" />
        </div>
    </div>

}
<table class="table table-striped">
    <thead class="bg-primary">
        <tr>
            <th>
                Client Name
            </th>
            <th>
                Phone Number
            </th>
            <th>
                Car
            </th>
            <th>
                Start Data
            </th>
            <th>
                End Data
            </th>
            <th>
                Price
            </th>
            <th></th>
        </tr>
    </thead>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Client.Name)
                @Html.DisplayFor(modelItem => item.Client.Surname)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Client.Phone)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Car.Brand)
                @Html.DisplayFor(modelItem => item.Car.Model)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartData)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndData)
            </td>
            <td>
                &euro; @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Rent_ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Rent_ID })
            </td>
        </tr>
    }

</table>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

RentCar/Views/Rents/OldUser.cshtml
@model RentCar.Models.Rents

@{
    ViewBag.Title = "OldUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid col-md-offset-4">
    @using (Html.BeginForm("OldUser", "Rents", new { carId = ViewBag.CurentCar.Car_ID }, FormMethod.Post))
    {
        <div class="form-group row">
            <div class="col-md-6">
                @Html.TextBox("searchPhone", null, new { @class = "form-control ", placeholder = "Phone number" })
            </div>            
            <div class="col-md-6">
                <input type="submit" value="Find" class="btn btn-success btn-md" />
            </div>
        </div>
    }
</div>


@using (Html.BeginForm("OrderOldClient", "Rents"))
{
    @Html.AntiForgeryToken()
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
            </div>

            <div class="col-sm-5">
                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @if (ViewBag.Client != null)
                    {
                        <h2> HI @ViewBag.Client.Surname !!</h2>
                        <h2>
                           Email: @ViewBag.Client.Email
                        </h2>
                        <h2>
                           Phone: @ViewBag.Client.Phone
                        </h2>
                    }
                    else
                    {
                        @Html.Raw("We have not been able to find users, please try again")
                    }

                </div>
            </div>

            <div class="col-sm-5">

                <div class="form-horizontal">
                    <hr />


                    <div class="form-group">
                        @Html.DropDownListFor(m => m.Car_ID,
                            new SelectList(ViewBag.Car, "Car_ID", "Brand", ViewBag.CurentCar.Car_ID),
                            "Change Car",
                            new {@class = "form-control", @placeholder = "Category"})
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.StartData, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>

                    <div class="form-group">
                        @Html.EditorFor(model => model.StartData, new { htmlAttributes = new { @class = "form-control", type = "date", id = "startData" } })
                        @Html.ValidationMessageFor(model => model.StartData, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EndData, htmlAttributes: new { @class = "control-label col-md-2" })
                    </div>

                    <div class="form-group">
                        @Html.EditorFor(model => model.EndData, new { htmlAttributes = new { @class = "form-control", type = "date", id = "endData", onchange = "CalculatePrice()" } })
                        @Html.ValidationMessageFor(model => model.EndData, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.CheckBoxFor(m => m.Driver, new { @style = "height: 17px" })
                        <label>Include driver</label>
                    </div>
                    <div class="PriceCarMain">
                        <h3 id="priceCalc">Total price: @ViewBag.CurentCar.Price &euro;</h3>
                    </div>
                    @if (ViewBag.Client != null)
                    {
                        @Html.HiddenFor(model => model.Client_ID, new {Value = ViewBag.Client.Client_ID});

                    }
                </div>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Send Order" class="btn btn-success btn-lg btn-block  center-block" />
        </div>
    </div>

}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script>
    function CalculatePrice() {
        var startData = $("#startData").val();
        var endData = $("#endData").val();
        var curentPrice = @(ViewBag.CurentCar.Price);
        debugger
        $.ajax({
            url: '/Rents/TotalPriceRent',
            type: 'POST',
            data:
            {
                startDate: startData,
                endDate: endData,
                price: curentPrice
            }
            ,
            success: function (result) {
                console.log("MDa");
                $("#priceCalc").html("Total price: " + result+" &euro; ");
            },
            error: function (err) {
                alert("error " + err.toString() + err.message);
            }
        });
    }

</script>