RentCar/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using PagedList;
using RentCar.Interfaces;
using RentCar.Models;


namespace RentCar.Controllers
{
    [Authorize(Roles = "Administrator, Moderator")]
    public class CarController : Controller
    {
        private readonly ICarRepository _carRep;
        private readonly ICategoryRepository _categoryRep;
        private readonly IGearRepository _gearRep;
        private readonly IFuelRepository _fuelRep;

        public CarController(ICarRepository carRep, IFuelRepository fuelRep, IGearRepository gearRep, ICategoryRepository categoryRep)
        {
            this._carRep = carRep;
            this._categoryRep = categoryRep;
            this._fuelRep = fuelRep;
            this._gearRep = gearRep;
        }

        // GET: CarCRUD
        public ActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(_carRep.GetAll().OrderBy(x => x.Brand).ToPagedList(pageNumber, pageSize));
        }

        // GET: CarCRUD/Details/5
        public ActionResult Details(int id)
        {
            
            return View(_carRep.GetById(id));
        }
        [Authorize(Roles = "Administrator, Moderator")]
        public ActionResult Create()
        {
            var enumData = from CarColors c in Enum.GetValues(typeof(CarColors))
                select new
                {
                  Name = c.ToString()
                };

            ViewBag.CarColors = enumData;
            ViewBag.Category = _categoryRep.GetAll();
            ViewBag.Gear = _gearRep.GetAll();
            ViewBag.Fuel = _fuelRep.GetAll();
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "Administrator, Moderator")]
        public ActionResult Create(Car car, HttpPostedFileBase file)
       {

            _carRep.Create(car);
            var lastCarId = _carRep.GetAll().Max(i => i.Car_ID);
            _carRep.UploadImageReturnID(lastCarId, file);

            return RedirectToAction("Index");
        }


        // GET: CarCRUD/Edit/5
        [Authorize(Roles = "Administrator, Moderator")]
        public ActionResult Edit(int id)
        {
            var enumData = from CarColors c in Enum.GetValues(typeof(CarColors))
                select new
                {
                    Name = c.ToString()
                };

            ViewBag.CarColors = enumData;
            ViewBag.Category = _categoryRep.GetAll();
            ViewBag.Gear = _gearRep.GetAll();
            ViewBag.Fuel = _fuelRep.GetAll();

            ViewBag.CategoryCurent = _carRep.GetAll().Where(i => i.Car_ID == id)
                .Select(s => s.Category_ID).FirstOrDefault();

            ViewBag.GearCurent = _carRep.GetAll().Where(i => i.Car_ID == id)
                .Select(s => s.GearType_ID).FirstOrDefault();

            ViewBag.FuelCurent = _carRep.GetAll().Where(i => i.Car_ID == id)
            .Select(s => s.FuelType_ID).FirstOrDefault();
            return View(_carRep.GetById(id));
        }

        // POST: CarCRUD/Edit/5
        [HttpPost]
        [Authorize(Roles = "Administrator, Moderator")]
        public ActionResult Edit(int id, Car car)
        {
            try
            {
                _carRep.Update(id, car);
                _carRep.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CarCRUD/Delete/5
        [Authorize(Roles = "Administrator, Moderator")]
        public ActionResult Delete(int id)
        {

            return View(_carRep.GetById(id));
        }

        // POST: CarCRUD/Delete/5
        [HttpPost]
        [Authorize(Roles = "Administrator, Moderator")]
        public ActionResult Delete(int id, Car car)
        {
            try
            {
                _carRep.Delete(id);
                _carRep.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RentCar/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using RentCar.Interfaces;
using RentCar.Models;
using RentCar.Repositories;

namespace RentCar.Controllers
{
    public class CityController : Controller
    {
        private readonly ICityRepository _cityRep;

        public CityController(ICityRepository cityRepo)
        {
            this._cityRep = cityRepo;
        }
        
        public ActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(_cityRep.GetAll().OrderBy(x => x.Name).ToPagedList(pageNumber, pageSize));
        }


        public ActionResult Create()
        {

            ViewBag.District = _cityRep.GetAllDistricts();
            return View();
        }


        [HttpPost]
        public ActionResult Create(City city)
        {
            try
            {
                _cityRep.Create(city);
                _cityRep.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {

                ViewBag.District = _cityRep.GetAll();
                return View(_cityRep.GetById(id));

        }


        [HttpPost]
        public ActionResult Edit(int id, City city)
        {
            try
            {
                _cityRep.Update(id, city);
                _cityRep.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(int id)
        {
            return View(_cityRep.GetById(id));
        }

        // POST: CityCRUD/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                _cityRep.Delete(id);
                _cityRep.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RentCar/Controllers/FuelController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using RentCar.Interfaces;
using RentCar.Models;
using RentCar.Repositories;


namespace RentCar.Controllers
{
    [Authorize(Roles = "Administrator, Moderator")]
    public class FuelController : Controller
    {
        private readonly IFuelRepository _fuelRep;

        public FuelController(IFuelRepository fuelRep)
        {
            this._fuelRep = fuelRep;
        }

        public ActionResult Index()
        {
            return View(_fuelRep.GetAll());
        }

        
        public ActionResult Create()
        {
                return View();
        }

        
        [HttpPost]
        public ActionResult Create(FuelType fuel)
        {
            try
            {
                _fuelRep.Create(fuel);
                _fuelRep.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        
        public ActionResult Edit(int id)
        {
            return View(_fuelRep.GetById(id));
        }

        
        [HttpPost]
        public ActionResult Edit(int id, FuelType fuel)
        {
            try
            {
                _fuelRep.Update(id, fuel);
                _fuelRep.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            return View(_fuelRep.GetById(id));
        }

        // POST: FuelCRUD/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
           try
            {
                _fuelRep.Delete(id);
                _fuelRep.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RentCar/Controllers/GearController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RentCar.Interfaces;
using RentCar.Models;
using RentCar.Repositories;


namespace RentCar.Controllers
{
    [Authorize(Roles = "Administrator, Moderator")]
    public class GearController : Controller
    {
        private readonly IGearRepository _gearRep;

        public GearController(IGearRepository gearRep)
        {
            this._gearRep = gearRep;
        }

        // GET: GearCRUD
        public ActionResult Index()
        {
            return View(_gearRep.GetAll());
        }

        // GET: GearCRUD/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GearCRUD/Create
        [HttpPost]
        public ActionResult Create(GearType gear)
        {
            try
            {
                _gearRep.Create(gear);
                _gearRep.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GearCRUD/Edit/5
        public ActionResult Edit(int id)
        {
             return View(_gearRep.GetById(id));
                
        }

        // POST: GearCRUD/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, GearType gear)
        {
            try
            {
                _gearRep.Update(id, gear);
                _gearRep.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GearCRUD/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_gearRep.GetById(id));
        }

        // POST: GearCRUD/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                _gearRep.Delete(id);
                _gearRep.Save();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RentCar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href='https://fonts.googleapis.com/css?family=Kanit' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Rubik Mono One' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">



    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript" src="@Url.Content("~/Scripts/RentCar.js")"></script>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"></button>
                @Html.ActionLink("RentCar", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                         @Html.Partial("_LoginPartial")

            </div>
        </div>
    </div>
    <div class="container-fluid">@RenderBody()</div>
    <div class="container body-content">
        
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

   
</body>
</html>

RentCar/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Kanit' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Rubik Mono One' rel='stylesheet'>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link href="@Url.Content("~/Content/AdminPanel.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="@Url.Content("~/Scripts/RentCar.js")"></script>
    @using Microsoft.AspNet.Identity

</head>
<body>
    
    <div class="sidebar">
        <div class="Admin-logo">
            <h5>@Html.DisplayName(User.Identity.GetUserName())</h5>
        </div>
        @Html.ActionLink("Statistcs", "AdminPanel", "AdminPanel", null, null)
        @Html.ActionLink("CAR", "Index", "Car", null, null)
        @Html.ActionLink("CATEGORY", "Index", "Category", null, null)
        @Html.ActionLink("FUEL", "Index", "Fuel", null, null)
        @Html.ActionLink("GEAR", "Index", "Gear", null, null)
        @Html.ActionLink("DISTRICT", "Index", "District", null, null)
        @Html.ActionLink("CITY", "Index", "City", null, null)
        @Html.ActionLink("CLIENT", "Index", "Client", null, null)
        @Html.ActionLink("ORDER", "Index", "Rents", null, null)
        @Html.ActionLink("DISCOUNT", "Index", "Discount", null, null)
        @Html.ActionLink("ROLE", "Index", "Role", null, null)
        @Html.ActionLink("USER", "Index", "User", null, null)
    </div>

<div class="content">
    <div class="row">
        <div class="col-sm-3">

        </div>
        <div class="col-sm-3">

        </div>
        <div class="col-sm-3">

        </div>
        <div class="col-sm-3">

        </div>
    </div>
    @RenderBody()
</div>

    

</body>
</html>